version: "3"

services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
    container_name: design_patterns_js
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev